### ISSUE TITLE
Render from Phoebus/CS Studio screen

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#103]
We would like to be able to render screens from Phoebus/CS-Studio.

The xml file they use should be loaded and rendered on the screen with a FromPhoebus type widget, based on FromJson.

This would be beneficial in terms of demonstrating that migration need not be difficult and that engineers could use the tools already provided by Phoebus to edit support module screens, for example.

The mood on this has changed in the last few weeks and it is now viewed as being an important part of a demo. We could use a simple Ion pump style screen for this which would be connected to a simulated IOC running with the PVA plugin.

**Comment by TimGuiteDiamond** [comment]
Phoebus *.bob format is *much* nicer than *.opi so I am just going to focus on that moving forwards.

[This package](https://www.npmjs.com/package/xml-js) might prove useful for converting the xml to JSON/JS objects.

**Comment by TimGuiteDiamond** [comment]
@willrogers with regards to pulling information out of the proptypes at runtime I think we might be out of luck quite early on: https://github.com/facebook/react/issues/5067

**Comment by willrogers** [comment]
We did find `parse-prop-types` before.

**Comment by TimGuiteDiamond** [comment]
This is the kind of info returned from [prop-parse-types](https://github.com/diegohaz/parse-prop-types):
```js
{
  name: {
    type: {
      name: 'string',
    },
    required: false,
    defaultValue: {
      value: 'Haz',
    },
  },
  show: {
    type: {
      name: 'oneOfType',
      value: [
        { name: 'bool' },
        { name: 'string' },
      ],
    },
    required: true,
  },
}
```

It is noteworthy that there have only been 4 releases to that package and the last one was in July 2018.

I do think that being able to dynamically perform different transformations on incoming information based on the prop type would be quite cool, but I'm not sure this is the right tool. It would require decoding this object as well as the object we are actually trying to parse. Or perhaps this is a viable option for a longer timescale.

Having some properties mapped to specific transformation functions seems like a good solution for the time being.

What do you think?

**Comment by willrogers** [comment]
I don't think we want to delve into serious prop-type parsing at the moment.

**Comment by TimGuiteDiamond** [comment]
Fair.

I'll move ahead with the function map then.

I think for a "production" version, this reflection of the widget object is something we would have to consider as it is not easy, and may be worth investigating one of the more general object description packages that are available, and customising it to suit our needs.

**Comment by TimGuiteDiamond** [comment]
This has been done to a significant level but is not entirely complete. However I believe it is at a satisfactory level for our demo.

@willrogers do you think anything needs to be urgently added to our bob rendering capabilities before closing this ticket?

**Comment by willrogers** [comment]
Mmm. There are a few things that aren't really functional still. Let's keep it open for now.

**Comment by TimGuiteDiamond** [comment]
Can we put together a specific list of things which don't work well yet?

- some actions?
- grouping container in OPI works differently that grouping container in Bob - use Display?
- BoolButton doesn't translate properly?

We have a long way to go, but the code does now support a basic subset of the Bob format, so a good start I think!

**Comment by willrogers** [comment]
One big one is that widgets may have references to the opi property name (e.g. `${pv_name}` `${background_color}`). Wherever we are changing the name or type of a property we will have to ensure that these substitutions are honoured. We probably want to move our format closer to the bob format.

Another example is more difficult: exit buttons are implemented by scripts in OPIs, so we can't translate them accurately. The best solution might be to add an exit action if CS-Studio and Phoebus are happy to accept it.

We should also be able to separate the opi and bob parsing code while sharing the parts that are common.

Finally, we should keep in mind the idea of parsing EDM files.

Plenty to do here and it's not just XML parsing. I might try to look at some of it before Christmas.

**Comment by willrogers** [comment]
The new file-parsing mechanism handles BOY and Display Builder files quite well. There will be improvements still to make but I am going to close this ticket.
