### ISSUE TITLE
Fix Circular Dependency in Dynamic Page

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#123]
There is a circular dependency in the DynamicPage component, as it uses widgetFromJSON to create the display widget, but widgetFromJSON also includes DynamicPage so that it can be specified in JSON files.

@skyfrench @willrogers any input on this would be appreciated as I don't see anything obvious.

See #101

**Comment by TimGuiteDiamond** [comment]
Have avoided this for the time being in #128 by ignoring the error.

This follows a conversation which @willrogers in which we agreed to tackle the larger issue with where the known components for rendering from files comes from by writing additional logic to get components from the store at runtime, thereby avoiding this type of dependency cycle.

Am leaving this issue open until that issue is written up, when it will be closed.

**Comment by TimGuiteDiamond** [comment]
Merged in #128

**Comment by willrogers** [comment]
Fixed in #133.
