### ISSUE TITLE
Refactor file layout

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#131]
Would be nice to clean up file layout.

Things have become quite tangled as we have worked towards a demonstrable prototype and we should have have clearer differentiation between different parts of the application, different types of widgets etc.

**Comment by willrogers** [comment]
Rough proposal:

```
App.tsx
connection/
redux/
types/
ui/hooks/
ui/pages/
ui/widgets/
ui/index.ts
ui/register.ts
ui/widget.tsx
ui/widgetActions.ts
ui/widgetProps.ts
```

**Comment by TimGuiteDiamond** [comment]
What would go in "ui/pages/" ?

**Comment by willrogers** [comment]
Maybe nothing if there are none any more.

**Comment by TimGuiteDiamond** [comment]
Yea I think the pages can - should? - all be defined in JSON now.

The public directory could also use some cleaning up, something like this?

```
/public...
  /json/
  /opi/
  /bob/
  /images/
```

**Comment by willrogers** [comment]
Done in #135.
