### ISSUE TITLE
Machine Status Screens

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#137]
We have many machine status screens at Diamond which display core pieces of information about how the synchrotron is operating at any given time. It would be a useful test of our prototype to replicate these screens on the web browser.

There are a couple of steps to this process:
- Directly render existing OPI files
- Recreate as bob files in Phoebus and render those
- Create new screens using modern design philosophy to demonstrate what we can do

**Comment by TimGuiteDiamond** [comment]
UX in Industry: https://www.uxmatters.com/mt/archives/2017/08/ux-for-the-industrial-environment-part-1.php
When and when not to use dark UIs (I think we fall in the don't category for most of our control screens): https://www.toptal.com/designers/ui/dark-ui

**Comment by TimGuiteDiamond** [comment]
Possible approach for displaying large amounts of data to the user: https://uxdesign.cc/designing-a-complex-table-for-mobile-consumption-nom-7472f7b11fe6

**Comment by TimGuiteDiamond** [comment]
Issues with initial bob conversion:
- widgets with default widths do not have a width attribute in the bob file, so default to 0
- fonts are not being converted (size, weight, font type)
- borders not being converted

**Comment by TimGuiteDiamond** [comment]
See latest changes on #167

**Comment by aawdls** [comment]
Implemented in a separate application.
