### ISSUE TITLE
Tabbed Container

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#168]
In an effort to improve the style and usability of our web application, supporting existing workflows based around the design of beamline screens in EDM and CS-Studio, I am suggesting here a specification for a tabbed container widget.

# Wireframe

See below wireframes with comments on how such a widget might work and how it could incorporate the beamline workflow.

![image](https://user-images.githubusercontent.com/50404435/81073712-f48db400-8edf-11ea-8230-d801a2ebc847.png)

![image](https://user-images.githubusercontent.com/50404435/81073756-02433980-8ee0-11ea-83f2-d1cc3526fdfd.png)

![image](https://user-images.githubusercontent.com/50404435/81073781-0cfdce80-8ee0-11ea-9cb8-c8b4931d4a8d.png)

# How does it work in EDM?

It is unlikely we will be able to, or even desire to replicate the EDM workflow.
EDM works by opening up a new application window for every component screen and detail screen, although it does put some effort into ensuring that a screen can exists as a singleton - i.e. pressing a button which opens a screen repeatedly will only create a singleton copy of the screen, and will bring it to the forefront of the display.

The `Related Display` widget which opens new screens allows the filename and macros to be set, along with other properties:

![image](https://user-images.githubusercontent.com/50404435/81074908-906bef80-8ee1-11ea-9e63-edf623e5add9.png)

Key macros are used to populate the new window, including the window title:

![image](https://user-images.githubusercontent.com/50404435/81075018-b5f8f900-8ee1-11ea-81cf-a7ef04dc4baf.png)

As the windows are operating separately, they can be safely closed in most instance without disrupting other screens.
This method also avoids the need to describe *where* a screen should open, as a completely new window will be created.

# How does it work in CS-Studio/Phoebus?

CS-Studio is built on the Eclipse framework, so comes with some built in methods for handling tabs, and targetting different areas of the screen.
The DLS-specific setup has split the screen up into sections, allocated to the synoptic, component and details screens separately.
However, this is by convention only.
We can see that when specifying the open OPI action, a limited number of possiblities are provided:

![image](https://user-images.githubusercontent.com/50404435/81075603-7aaafa00-8ee2-11ea-9a69-caf1d25ed0aa.png)

Phoebus also allows a limited number of options:

![image](https://user-images.githubusercontent.com/50404435/81076207-4be15380-8ee3-11ea-941f-f7406304b790.png)

Of interest is the `Pane` option. A pane appears to be essentially a container which can have tabs in it (sound familiar) and can be given a specific name: https://control-system-studio.readthedocs.io/en/latest/docking.html?highlight=pane#named-panes.
I do not believe this capability has been investigated deeply at DLS.

The *name* of the screen, or tab, is specified in the `name` attribute of the top level `display` component in the xml file which specifies the screen:

![image](https://user-images.githubusercontent.com/50404435/81076624-c27e5100-8ee3-11ea-8c7a-5517b1317004.png)

# Prior Art

There are many tabbed container packages available for download via npm.
Here I will offer some links and short reviews:

## Bootstrap

https://react-bootstrap.github.io/components/tabs/

Looks nice, does not have obvious way to close tabs. This could be implemented.

## Material  UI

https://material-ui.com/components/tabs/

Much the same as above

## React Tabs

https://reactcommunity.org/react-tabs/

Also looks nice but depends on strange dependecy of 4 different widgets, might be better for static pages?

# Possible challenges

- how are we going to open new tabs in the correct container? We need to have an action of some sort we can pass in to widgets. Currently the `DynamicPage`, a similar widget in many ways, uses the URL to hold this state. This has the benefit of being able to recreate a screen set up by copy-pasting the URL. Another approach would be to use the Redux store, actions, reducers and the like. This would hide the mechanism from the user but we could offer a button or link to copy a representation of the screen to a url which would then be decoded at the other end and turned back into Redux state.
- tabs need to be able to open and close dynamically in a clear and obvious manner
- what happens when many tabs are open? Should we squeeze them all in, should they overflow into a scroll bar?
- where does the tab name come from? We currently lack the specific mechanism used by CS-Studio as we do not specify the top level widget and we also do not have a "name" attribute. We also might find it difficult to introspect the file/generated widgets to extract this information. The EDM mechanism (where this information is stored in the action) would be easier to implement but to my mind makes a bit less sense?

# Steps to implementation

I think it makes sense to build a tabbed container from the ground up, at least initially, so that we can work out these issues without the extra capability offered by some of the above packages.
Here are some milestones we can aim for:

1. Simple stateful tabbed container which can swap between hardcoded child elements
2. Add opening and closing of new tabs.
3. Add action to open and close new tabs.
4. Use tabbed container with existing screen files.

# Comments welcome!

**Comment by TimGuiteDiamond** [comment]
Further analysis of CS-Studio and Phoebus

# CS-Studio

Tabbed container widgets exist but are relatively basic. To embed a screen you need to add a linking container widget inside and you cannot (as far as I can tell) dynamically open or close tabs.

OPI files can be opened in pre-defined areas such as Workbench, Replace Current, New Window etc. These appear as tabs in their relevant sections and can be closed or used to open new tabs.

# Phoebus

Phoebus has tabbed containers and "Navigation Tabs" which is basically a specialised tab container in which each tab opens a specific file with associated macros. It does not appear to be possible in Phoebus either for tabs to be dynamically opened or closed through the use of other buttons.

However, the top-level Phoebus layout looks a lot like a Navigation Tab, but does have the ability to open and close tabs, so I wonder if it has been implemented as a special case which can hold some extra state?

There is also the concept of "panes" - see [this link](https://control-system-studio.readthedocs.io/en/latest/docking.html?highlight=pane#named-panes) - however it is not obvious how to create new panes with specific names. It appears that once this is done, specific panes could be addressed by some particular name and therefore tabs could be made to open there.

**Comment by TimGuiteDiamond** [comment]
# Encoding tabs in Phoebus

Tabs in Phoebus are encoded as a list of `<tab>` tags, with children where necessary.
The Navigation Tabs widget is encoded similarly, with file information instead of children.

```xml
<tabs>
      <tab>
        <name>Tab 1</name>
        <children>
          <widget type="label" version="2.0.0">
            <name>Label_1</name>
            <text>Tab 1</text>
            <x>88</x>
            <y>60</y>
          </widget>
      </tab>
</tabs>
```

**Comment by TimGuiteDiamond** [comment]
# Handling Recursion

There is a potential issue with tabs and embedded screens in general - what happens when a tab requests that the file containing it be shown inside it's body?

We can see that this will quickly lead to an infinite loop, which is usually considered a bad thing.

So, what is the best way to handle this? Let's take a look at the existing display managers:

# Phoebus

Initially, Phoebus handled this relatively well and seemed to be fine, however it clearly does not have a maximum limit of any kind and so after scrolling down a bit to find the innermost copy of the file, it failed.

![image](https://user-images.githubusercontent.com/50404435/82547404-943e7980-9b51-11ea-9b79-e7e8a69fc09b.png)

No warning message was displayed in Phoebus itself, but error messages can be seen on the console.

![image](https://user-images.githubusercontent.com/50404435/82547481-bc2ddd00-9b51-11ea-8166-4fa8f92a34b7.png)

# CS-Studio

CS-Studio renders the first level of recursion, but then notes that there is a loop and refuses to continue.
The application remains functional and there is a useful warning message within the application console.

![image](https://user-images.githubusercontent.com/50404435/82547869-50983f80-9b52-11ea-98b2-0d307c25e3de.png)

Warning message:

![image](https://user-images.githubusercontent.com/50404435/82548026-8fc69080-9b52-11ea-8cf0-3924cf19b9a3.png)

# EDM

EDM takes a bit of coaxing to do this but the Embedded Window widget does the job.
Similarly to Phoebus, it does not fail obviously, although it gradually becomes less and less responsive.

![image](https://user-images.githubusercontent.com/50404435/82552813-c0122d00-9b5a-11ea-9275-4f4bee67a557.png)

When trying to exit the program, an error is shown. The program must be killed at the terminal.

![image](https://user-images.githubusercontent.com/50404435/82552830-c86a6800-9b5a-11ea-851c-e6ef907483e2.png)

# CS-Web-Proto

So, what should we do? I think CS-Studio handles this the best - perhaps this logic will find it's way into Phoebus soon enough as well.
We need to think about how this would be handled.

**Comment by willrogers** [comment]
I'm trying to think through the use cases here. I come down to:

* 'section': this is the dynamic page widget and has a `location`
* 'tabbed section': similar to the dynamic page widget but additional pages could be opened in tabs
* 'named tab section': pages can be opened in named tabs
  * could this just be widgets in named tabs, and the widget could be just a 'section' with its own `location`

Then the OPEN action:

```
file: ...
type: ...
location: ...
macros: ...
```

CLOSE action:

```
location: ...
file: ...  # optional?
```

How many use cases would this meet?

**Comment by TimGuiteDiamond** [comment]
I think the above is quite similar to what I have implemented in terms of open and close tab actions. I'll keep experimenting to see what I can get to work and then take a look back at how we can perhaps merge the schemas for the different actions.

There are some complications such as what happens if you calll the `CLOSE_PAGE` action on a tabbed container? It doesn't have a way to close, but it's information will be lost from the state (held in the URL) which will close all the tabs. We also can't verify all this information statically because which containers are availale at any given time is dynamic depending on which screens are open.

Another potential problem I can think of: you have a screen with a tab container, and you instantiate it twice with different macros - from the URL it is not possible (at the moment) to tell in which container tabs should open.

**Comment by willrogers** [comment]
I think we should move to using a context rather than the URL to hold the information that we need. We may return to using the URL but at the moment it is making it more difficult for us to decide the information that we are trying to encode.

**Comment by TimGuiteDiamond** [comment]
We would still have a similar problem though, wouldn't we?

A possible solution (in the future) would be to use a context or Redux object to store this information and offer a "share" button which exposes an encoded url. However, the challenge is deciding what goes *into* the context. The dynamic tabs are working now, although the schema doesn't match up that well with opening pages. Requires further thought.

**Comment by TimGuiteDiamond** [comment]
Following our discussion, identifying pages by the file information (filename, filetype, macros) should work, but there is one remaining question: where should the tab name come from? I think in CS-Studio this is provided through the `$(desc)` macro, although I'm not sure if that is a CS-Studio thing or a Diamond thing? Should we require a `name` parameter for all screens, including times when it is not used at the moment (such as a basic embedded display)?

**Comment by willrogers** [comment]
Now working nicely.
