### ISSUE TITLE
Device widget

### ISSUE THREAD

**Issue by willrogers** [dls-controls/cs-web-proto#174]
Create a widget that can sensibly display all fields for a 'device'.

Devices are in the [GraphQL schema](https://github.com/dls-controls/coniql/blob/tartiflette/coniql/schema.gql) but are not yet queried inside `coniql.ts`. The existing code can be extended to get the device information.

Channels currently have hints for the type of widget that should be used within their display field.

**Comment by willrogers** [comment]
This needs to be on top of the `tartiflette` branch at present.

**Comment by aawdls** [comment]
We are not currently planning to support devices in this sense and they have been removed from coniql.
