### ISSUE TITLE
Unreleased version of react-tiny-popover

### ISSUE THREAD

**Issue by willrogers** [dls-controls/cs-web-proto#243]
The latest version of react-tiny-popover (6.0.5) requires React v16. The master branch has been updated to allow React v17.

To allow updating React I have pushed my own version to Github, and I am installing directly from there, but we should switch back to the released version when possible.

**Comment by aawdls** [comment]
@rjwills28 I assume this will be resolved with #263

**Comment by rjwills28** [comment]
Yes it would but looks like Will had already fixed this anyway in commit 'Reinstate production build of react-tiny-popover' - see https://github.com/dls-controls/cs-web-proto/commit/2a42c65876a58f4ed56b3b122204163881e91eb8.
Closing this issue.
