### ISSUE TITLE
Add a wiki page describing the development environment

### ISSUE THREAD

**Issue by willrogers** [dls-controls/cs-web-proto#28]
We should describe the development environment in a Github wiki page so that it is available to outside collaborators.

**Comment by TimGuiteDiamond** [comment]
Created this page, let me know what you think

**Comment by willrogers** [comment]
https://github.com/dls-controls/cs-web-proto/wiki/Development-Environment

**Comment by willrogers** [comment]
This looks good, we can update it as necessary.
