### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by willrogers** [dls-controls/cs-web-proto#36]
We are using Prettier, but we still have quite a few irregularities in the code, filenames being one.

I suggest we follow https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md, and make any further updates to [this wiki page](https://github.com/dls-controls/cs-web-proto/wiki/Style-guide).

https://www.npmjs.com/package/eslint-plugin-filenames may help.

**Comment by TimGuiteDiamond** [comment]
Cannot work out how to properly implement this eslint extension, does not seem to want to behave. Will try again on Monday.

**Comment by TimGuiteDiamond** [comment]
Figuring this out took me quite a while@:
https://github.com/eslint/eslint/issues/9330

So the glob expression will now be wrapped in single quotes
