### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#38]
Through the use of multiple networks with different access privileges, it is often possible to view PVs but not provide input to them.

We need to explicitly allow for this setup.

It would also bee nice if we could implement a different mouse pointer of some kind to display to users that they cannot write to a PV (and to prevent them being able to use the PV) - similar to CS-Studio.

**Comment by talwrii** [comment]
See the [cs cursor](https://www.w3schools.com/cssref/pr_class_cursor.asp) property. The not-allowed value might be appropriate.

**Comment by willrogers** [comment]
The other question is: how do we know that we don't have write permission?

We should investigate how Phoebus does the same thing.

**Comment by willrogers** [comment]
See also #53.

**Comment by TimGuiteDiamond** [comment]
ReadOnly was implemented although can't find the exact PR

@willrogers, I think you added this?

**Comment by willrogers** [comment]
Yep this is done.

**Comment by talwrii** [comment]
> ReadOnly was implemented although can't find the exact PR

`$git log --merges --grep readonly -n 1
commit b0ec1e116545b6ea8a7e6a7f300914e57b2f7fbd
Merge: 4c0a2a1 8d6f573
Author: Will Rogers <will.rogers@diamond.ac.uk>
Date:   Mon Oct 21 10:50:06 2019 +0100

    Merge branch 'readonly' into talwrii--issue-35--simulator-refactor
```
