### ISSUE TITLE
PV State

### ISSUE THREAD

**Issue by willrogers** [dls-controls/cs-web-proto#53]
A PV may have a particular value (represented by a VType), but that doesn't include whether the PV is connected or whether it is readonly. These are additional information associated with each PV.

At the moment in the store we have 

```
export interface PvState {
  value: VType;
  connected: boolean;
}
```

We could add `readonly: boolean` to this. Looking at the `PV.java` class in Phoebus, the only other state associated with the PV is the list of subscribers. We currently have this as a separate object in the store.

Another important point is that the vtype may be null (this happens for example when a local PV has not been initialised). That suggests that the pv state should be:

```
export interface PvState {
  value?: VType;
  connected: boolean;
  readonly: boolean;
}
```

with a value that may be undefined.

**Comment by TimGuiteDiamond** [comment]
How does Phoebus tackle this problem then? Or are you saying this IS a state stored with the PV state information in Phoebus?

**Comment by willrogers** [comment]
Phoebus has a PV object, which has:

* a value (VType) that may be null
* `isDiconnected()`
* `isReadonly()`

**Comment by TimGuiteDiamond** [comment]
Main work here would be adding it in connectionWrapper.tsx and giving a sensible name?
Are there any places where this would be expected to cause big problems?

Happy to take this on as I haven't looked at this part of the program too much.

**Comment by willrogers** [comment]
I think this would be quite simple. I'm not sure what you mean by 'giving a sensible name' though.

**Comment by TimGuiteDiamond** [comment]
Will this need to be optional? Can a PV which is not connected know whether it is readonly or not? Should this default to True if there is no connection or other information from the PV?

**Comment by willrogers** [comment]
Same in CS-Studio.

**Comment by TimGuiteDiamond** [comment]
Yea I'm happy with that. Are we envisioning that this information will eventually be sent from the EPICS interface (ie coniql) ?

**Comment by willrogers** [comment]
Yes, it comes through coniql. It will be false for local PVs, but we could have sim pv for which it is true.
________________________________
