### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by willrogers** [dls-controls/cs-web-proto#55]
Rules allow changing any property based on the value of different PVs. They are encoded in the `.bob` file format.

This should be possible with a wrapper component. The type of the property is important.

**Comment by TimGuiteDiamond** [comment]
Will this be able to change the name of the PV which the element is interested in? If so might it need to be a HOC wrapped around macro and connection wrappers?

**Comment by willrogers** [comment]
So, I have thought about wrapper components and props and higher-order components.

The difficulty with wrapper components is that you can't edit the props that children get when you render `{props.children}`. This works ok when you are just _using_ props (like in the PV copy, which uses the PV name, and the tooltip, which uses the name and value). It doesn't work for the connection wrapper, which requires a PV name but needs to add the value as a prop, or the macro wrapper which needs to change the values of props.

[This blog post](https://frontarm.com/james-k-nelson/passing-data-props-children/) among others describes this problem.

The way I have managed this is to use the so-called 'higher-order components'. These take the component as an argument and then render that component with any additions or changes to the props. Since the natural way to define rules modifies the props for children we should probably use a similar HOC. See `src/Components/ConnectionWrapper/connectionWrapper.tsx`.

@skyfrench @TimGuiteDiamond

**Comment by willrogers** [comment]
Here's a snippet from a Phoebus XML file. The rule is the one that changes x position based on the value of the PV.

```
    <rules>                                                                     
      <rule name="xpos" prop_id="x" out_exp="true">                             
        <exp bool_exp="true">                                                   
          <expression>pv0*100 + 100</expression>                                
        </exp>                                                                  
        <pv_name>sim://sine</pv_name>                                           
      </rule>                                                                   
    </rules> 
```

**Comment by TimGuiteDiamond** [comment]
Added in #76

**Comment by TimGuiteDiamond** [comment]
Only allows individual rules now, not multiple rules

**Comment by willrogers** [comment]
We now have a more sophisticated rules mechansim.
