### ISSUE TITLE
Support phoebus simulator pv's

### ISSUE THREAD

**Issue by talwrii** [dls-controls/cs-web-proto#66]
See #35.

This page from the Phoebus documentation talks about both sim and loc PVs. We should try to support what Phoebus supports:

https://phoebus-doc.readthedocs.io/en/latest/phoebus/core/pv/doc/index.html

**Comment by talwrii** [comment]
This depends on #35

**Comment by talwrii** [comment]
This includes a small change to coniql subscription. 

This branch should be tested against coniql before merging.

**Comment by willrogers** [comment]
Can you open a PR?

**Comment by talwrii** [comment]
Yep. You can look at what's implemented so far.

I've just implemented a way of preventing duplicated initializaitons but this isn't working yet.

**Comment by willrogers** [comment]
Let's close this and add further ones as we think they are necessary.
