### ISSUE TITLE
Simulator -- Delete pv's on unsubscibe

### ISSUE THREAD

**Issue by talwrii** [dls-controls/cs-web-proto#68]
Subissue of #35.

**Comment by talwrii** [comment]
I'm not sure how necessary this code is.

Presumably the simulator normally has the same life cycle as the react App component. The only time that this wouldn't be the case is if we were creating components with different pvNames. 

On the other hand it is easy to implement...

**Comment by talwrii** [comment]
See #80

**Comment by willrogers** [comment]
I'm not sure how necessary this is, but now merged.
