### ISSUE TITLE
Runtime type checking

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#69]
It would be good to be able to validate data coming from JSON to guarantee that the necessary props are being passed to widgets.

This requires runtime validation against types/interfaces which, unfortunately, appears to be *very* difficult in typescript. It is a "non-goal" of the language (https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals non-goal 5).

The solutions vary from including a "type" field in all interfaces which may only have one value (https://www.matthewgerstman.com/tech/ts-tricks-type-guards/) this seems insufficient for us.

Then there are many middlewares which offer to do both static and runtime type checking, the library of the day seems to be io-ts (https://github.com/gcanti/io-ts). This would not be a minor change and would represent a relatively significant reliance on a library which may or may not continue to be supported moving forwards.

I haven't found any other great ideas other than very manual processes so any help would be much appreciated.

**Comment by willrogers** [comment]
Yes, I was thinking that this would happen. Of course, if we try to use the TypeScript types then we can't support plain JavaScript widgets either. So perhaps that's not the best way.

We might be able to go the other way round. You can do type checking on components in JavaScript using [proptypes](https://www.npmjs.com/package/prop-types). You then seem to be able to infer the TypeScript type from the prop types using [inferProps](https://dev.to/busypeoples/notes-on-typescript-inferring-react-proptypes-1g88). And I think you can get at the prop types at runtime for e.g. editor purposes (e.g. [parse-prop-types](https://github.com/diegohaz/parse-prop-types)).

It's not fully clear that all the pieces we need are there, but they certainly might be.

**Comment by TimGuiteDiamond** [comment]
Just had a quick look now but seems like a react-specific flavour of the above libraries? Perhaps that will be enough.

Could support JS by requesting an interface type object alongside the widget and if there isn't one then allowing all props through without an error?

**Comment by talwrii** [comment]
Some thoughts:

* When do we want to error to occur? One thing we might want to do here is ensure that the error happens immediately on passing the errors. What does this mean for doing the checking on components? This might be okay if we create the components immediately on loading the JSON.
* Clear error messages. If we have lots of similar objects we want to be able to point the user / developer at the correct nested JSON object and potentially the correct line. One way of achieving this is to wrap our rendering components with wrappers that will print the path to an element on error.

**Comment by TimGuiteDiamond** [comment]
I think that when we use this project in production, it is quite likely that **all** of the screen will be loaded from JSON so the errors should be caught when the JSON is loaded. There is a question about how to show the error to the user, I guess at the least we can log the error but perhaps we can also provide an error notification of some kind with more specific information about the error which occured.

JSON schemas are another way to tackle this problem, I'm going to investigate using prop types first but that is on my radar and might turn out to be more useful in the long run.

**Comment by willrogers** [comment]
Screens will be loaded from JSON, but we want to be able to ask a widget at runtime what its props are and what their types are. This is important e.g. for a screen editor. So the widget would need to store its own schema and you would need to query it.

**Comment by TimGuiteDiamond** [comment]
Works relatively well now but we want to add a bit more work to reduce the amount of repeated code when defining interfaces for widgets.

This will require adding some more interfaces with specific names and some additional prop types too.

**Comment by TimGuiteDiamond** [comment]
@willrogers We might run into a problem trying to convert everything to PropTypes - PvState for instance uses VTypes, and I really do not want to go around using PropTypes there. I will use a workaround for the time being so we can see what it looks like.

**Comment by TimGuiteDiamond** [comment]
@skyfrench I have now pushed my latest changes to #84 and updated the wiki with what I hope is correct information. Please have a go at using this to create a shape widget and let me know how it goes. Once you have created it I can show you how to add the type checking (only performed for a specific number of widgets at the moment) and we can evaluate.

**Comment by TimGuiteDiamond** [comment]
This now performs a good level of checking on most of the embedded objects we have specified, such as containerStyling and catches missing required keys such as "text" in the Label widget, but it will not catch extra keys at the top level of the widget description.

This could perhaps be performed with [prop-types-exact](https://github.com/airbnb/prop-types-exact), although it is not clear whether this package is kept up to date.

**Comment by TimGuiteDiamond** [comment]
Merged this in #84 , but further work could be done. This is a working mechanism for validating widget descriptions as JSON at runtime.
