### ISSUE TITLE
Potential Collaborations

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#71]
Just raising this to remind us to review the ICALEPCS presentations for similar projects which are being developed at other facilities.

It appears that there is more than a bit of overlap between projects and it will be interesting to see how for along our prototype is compared to others and which parts we could borrow or interface to.

**Comment by willrogers** [comment]
From the EPICS mailing list:

> Hi All
We have released our new software platform to enable EPICS control through a progress web application.
We have called it React-Automation-Studio and it is available as a Git mono repo at https://github.com/wduckitt/React-Automation-Studio
Check it out and follow the README for installation instructions.
There is also a template repository at https://github.com/wduckitt/React-Automation-Studio-Example-Project-1 which pulls in the main repository as a submodule. You are free to copy this repository and customize it to your lab.
Contact us rasadmin@tlabs.ac.za if you would like to become a contributor!
Regards,
William

**Comment by TimGuiteDiamond** [comment]
Certainly seems to be quite advanced and to have more widgets than we do.
Also good props to them for making it look nice.

However, just looking at their textinput, there is a lot of state going on! Perhaps there is some value we can add to the project with our slightly different approach.

**Comment by TimGuiteDiamond** [comment]
They are using propTypes tby the look of it #69

**Comment by willrogers** [comment]
I have created a wiki page [here](https://github.com/dls-controls/cs-web-proto/wiki/Existing-applications) that we can update as appropriate, so I will close this ticket.
