### ISSUE TITLE
Allow the simulator to simulate arbitrary process variable names rather than sim://name

### ISSUE THREAD

**Issue by talwrii** [dls-controls/cs-web-proto#78]
This could be achieved with a JSON file or similar.

I don't know how worthwhile this is. It would allow one to prototype for a real control system without the control system being present. Is this a real use case?

# Reusing existing simulator specification

Since we already have a way of specifying the behaviour of process variable through pvName's with initialization strings (e.g. "sim://sine(variables)") and we are required to support these for backwards compatibility with phoebes, it might make sense to keep these initialization pvNames for configuration.

So, the json file might look something like:

```
{
  "PV1": "sim://sine"
  "PV2": "sime://sine(1, 2)"
}
```

There are a few issues with this approach (that I can see)

* There is some implicit extra validation to using json strings rather than raw strings, which can make identifying errors easier. Compare, for example, `"sim://sine(1 2, 3)"` to `{simulator: sine, min: 1 2, max:3}`
etc
* We might end up reimplementing `JSON` for complicated parameters.

# Supporting arbitrary simulators

It might be nice to be able to point at javascript code for simulation. This in theory allows one to have correlated values.

{ 
  "PV1": "code://state.pv1",
  "PV2": "code://state.pv2",
  "PV3": "code://pv3"
}

I imagine this is beyond scope. We might prefer to provide people with an easy way of providing their own simuations.

**Comment by willrogers** [comment]
I don't think that we want to support this. Simulation PVs are useful for development but they won't be used in production, and this adds more complication.

Simulating a real control system is not a job for this simulator.
