### ISSUE TITLE
Performance Testing and Improvements

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#94]
We would like to understand how well this prototype performs when presented with a large number of PVs which are updating at a significantly high rate. This will also be of interest to many of the engineers who might use this type of program in the future.

[This paper](https://github.com/dls-controls/cs-web-proto/wiki/files/epics-ui-performance.pdf) provides a "standard" performance metric for comparing different EPICS GUI interfaces and is a useful starting point for future comparisons.

One prerequisite for performance testing is producing many PVs which can update at a significantly high rate. We can provide a first pass at this using the simulator.

Beyond this, we will need to use a database to generate actual PVs and connect to them. Our current Coniql plugin uses PVA, so we could set it up with an EPICS7 IOC with all these PVs and connect to that. It should also be possible to connect to that IOC from CS-Studio and Phoebus.

Tom Cobb will also provide advice and reference on previous GUI tests which were performed at Diamond and that information will be recorded here.

**Comment by TimGuiteDiamond** [comment]
In addition to the above testing, some effort will be made to improve the efficiency of our React code. Most gains in this domain come from being able to reduce the number of times a component re-renders itself.

There are some strategies around this - [here](https://hackernoon.com/react-performance-primer-64fe623c4821) for example - however all optimisations have situations in which they work and situations in which they don't, and it is quite likely that our core program architecture could benefit from improvement before we begin chasing these gains. Nevertheless, it would be instructive to see where some of these optimisations can be useful and where they have a negligible or negative impact. This will be informed using the testing methods listed above.

**Comment by TimGuiteDiamond** [comment]
Have been pointed towards using Python Soft IOCs to provide the requisite number of identical and similarly named PVs. Will also create a script to help me generate similar layouts of screens for CS-Studio, EDM and CS-Web-Proto.

**Comment by TimGuiteDiamond** [comment]
Have written a script to perform this task, preliminary testing suggested that we have a lot of unnecessary re renders happening in the widgets which is massively slowing down performance, relative to CS-Studio.

This performance will be captured on a separate branch and recorded.

I will investigate a number of strategies to try and improve this performance:
- Use a simulation PV to remove potential slowdown as a result of ConiqlPlugin
- Use of React.memo and useMemo to test changes on inputs
- Custom memo checkers to expand embedded objects in the widget interface
- Flatten widget interface to allow prop checking to work better with a shallow check, thereby avoiding the need for custom checkers

A record of the approximate performance with the units provided in the paper referenced above will be taken.

**Comment by TimGuiteDiamond** [comment]
Have implemented simulated ramp PV and performance appears to be slightly improved over using Coniql although there is an inevitable slow down as more PVs are added and more PVs are required to be processed, presumably due to the single threaded nature of JS.

Replacing this code with calculations on a `new Date()` object caused further disruption, perhaps because calculating Date is computationally heavy? This led to very disrupted behaviour of the widgets.

**Comment by TimGuiteDiamond** [comment]
Removing hooks from Widget brings the longest render with a single Readback down to 5ms with this all concentrated at the PVWidget and below. Perhaps these values can be memoized?

**Comment by TimGuiteDiamond** [comment]
- With 10 Readbacks this is 4ms and again, all renders are at PVWidget level and below.
- With 50 Readbacks 4ms is also the given time although the program is slowing down due to continuously updating more PVs. Renders are at PVWidget level and below.

**Comment by TimGuiteDiamond** [comment]
Applying a memo to Widget which expands all of the internal objects appears to be a step in the right direction as calling the memo function is much faster than re rendering the widget, however the DisplayComponent itself is still re rendering on every cycle.

**Comment by TimGuiteDiamond** [comment]
Seems to perform a bit better with Coniql but still can't handle 50 PVs at 10 Hz. This can actually freeze the server which will then not refresh and must be manually restarted (far from ideal).

**Comment by TimGuiteDiamond** [comment]
`useRules` hook was triggering Widget re renders so have removed for the time being. Can now adequately support 25 PVs at 10Hz with occasional jumps.

Interested to see what performance was like without hooks so am going to branch off from master before the hooks branch was merged to investigate how HOCs impacted this.

**Comment by TimGuiteDiamond** [comment]
Seems that HOCs are providing much of the benefits of the above changes, without all the memos and spread operators! See *performance-hoc* branch They do avoid rules though, should check if removing rules and memos etc from the performance branch has the same benefit.

In the meantime, value change is causing connectionWrapper, Widget and Readback component all to render - is there a way we could refactor widget to put useConnection only around the components which actually need it? Will investigate.

**Comment by TimGuiteDiamond** [comment]
Achieved this with a bit of a hack but I think this could be expanded to get the full functionality that we had before without too much hassle.

Seems that ConiqlPlugin may be the source of some latency as this is visible even when the update rate of the database itself is slowed down to 2 seconds per update.

**Comment by TimGuiteDiamond** [comment]
Have made some decent progress on this - see #98 - but it seems the problems may lie elsewhere.

@willrogers @talwrii would it be possible to do some performance testing of the Coniql connection itself, especially as the number of PVs requested increases? I can have a go at this but it is not my speciality. When the number of PVs is ~100 the browser itself starts to become unresponsive which makes me think we are filling the event queue up, although not sure on the specifics.

**Comment by TimGuiteDiamond** [comment]
@willrogers the latest commit on #98 does indeed show a Readback component with a "flat" props interface, which removes renders due to changes in style. Changes are only triggered by a change in value.

This is a possible implementation which mixes our existing grouped prop types with the shallow comparisons required by React for easy performance gains.

**Comment by TimGuiteDiamond** [comment]
![Capture](https://user-images.githubusercontent.com/50404435/68602343-10b71800-049e-11ea-9c0d-515ddad78050.PNG)

This capture is from one render caused by a PV value update, the render parts on the widget and readback took 4.15ms and 1.33ms respectively. Perhaps there is a way we can add the connection hook without causing the entire PV Widget to re render?

**Comment by TimGuiteDiamond** [comment]
![Capture](https://user-images.githubusercontent.com/50404435/68665990-f7b07480-053a-11ea-8652-7f7de90dd505.PNG)

As you can see here, taken from the performance-hoc branch, the connection hoc seems to perform better, less than 1ms per render. I think it might be useful to use this to separate the structural part of a PV Widget - wrappers, props, styling - from the connected part. However, it is also a very stripped down example without the same capabilities, such as rules, so is not necessarily an identical test. Further work is needed,

The idea is to provide the hooks at the lowest possible level, particularly to prevent using the recursive wrapping function repeatedly where it is not needed.

**Comment by TimGuiteDiamond** [comment]
![Rules1](https://user-images.githubusercontent.com/50404435/68674817-811d7200-054e-11ea-8652-4b1b9a5e79d7.PNG)
Using the same machine, it appears that the new rules hook version is nearly as fast, down to around 1ms so the previous timing could have been a machine dependent measurement. I can also confirm again that the display widget is not being re rendered.

**Comment by TimGuiteDiamond** [comment]
![MultipleWidgets](https://user-images.githubusercontent.com/50404435/68677866-bd53d100-0554-11ea-9db5-e0f4a9642bbe.PNG)
It can be seen here with three widgets each reading different PVs that each PV update is causing each PV to update every time (below React Tree Reconciliation). Therefore our scripting is taking ***O**(n<sup>2</sup>)* time where *n* is number of elements.

**Comment by TimGuiteDiamond** [comment]
![MultipleWidgetsOnePV](https://user-images.githubusercontent.com/50404435/68678214-70242f00-0555-11ea-934c-ec2f50ebe9b3.PNG)
Contrast that with this example where all the widgets are looking at the same PV. As expected, the PV update causes the widgets which are subscribed to render. This, combined with the above example, suggests that **ANY** value update in the cache is causing **all** PV widgets to update.

Will investigate this further.

**Comment by TimGuiteDiamond** [comment]
See #98 to replicate this

**Comment by TimGuiteDiamond** [comment]
![MultipleWidgetsUnconnected](https://user-images.githubusercontent.com/50404435/68679418-bbd7d800-0557-11ea-9c11-c0f794738ff7.PNG)
This looks like a smoking gun to me: three widgets, one connected to sim://ramp#01, the others connected to loc://pv1 and loc://pv2 respectively. The local pvs will never update in this example. The update of the ramp PV triggers the other two PVWidgets to update.

Therefore, we have a situation where the number of updates performed when a PV value is updated is proportional to the **total number of subscriptions** rather than the **number of subscriptions to that PV**.

**Cons**: This is clearly not optimal
**Pros**: We can fix this

**Comment by TimGuiteDiamond** [comment]
My immediate suggestions:
1. Find the code which is causing all of the listeners to be triggered (this is likely to do with the shallow comparison we faced earlier) and fix it so that only Widgets which are subscribed to PVs that have changed in **value** are updated
2. Throttle the updates from the store (or renders) to once every 100ms and then release all changes at the same time - this is the fastest a normal PV is allowed to update and could prevent multiple different render triggers overlapping and filling up the event queue

**Comment by TimGuiteDiamond** [comment]
![middlewareFunctions](https://user-images.githubusercontent.com/50404435/68682026-5e925580-055c-11ea-9287-6bde97803e41.PNG)
@willrogers these are the functions and files referenced in Chrome devTools under the event log tabs and line up with the blue segments in the image above underneath **Function Call** - note that I changed valueChanged to valueChangedThisIsInMiddleware

**Comment by TimGuiteDiamond** [comment]
![MultipleWidgetsOnePVOneRender](https://user-images.githubusercontent.com/50404435/68685823-9b614b00-0562-11ea-8a1c-a393993cc5c2.PNG)
Latest change in #100 appears to effectively prevent unncessary re renders of the PV widgets which are subscribed to values which have not updated. See the above graphic from #98.

Used a similar fix to #99 to check that the value has actually changed. Clearly this is a recurring theme so we should be careful in the future not to re introduce this bug. Further testing is required to see how this affects performance with a large number of PVs.

**Comment by TimGuiteDiamond** [comment]
Have explored the latest changes with respect to the system before the connection hook was changed. Tested different numbers of widgets each connected to their own PV. The measurements below are semi scientific measurements from the latest commit at this point and the change before the hook was merged, of total render time of one update. Sim is set to update every 5s so the gap between update cycles is clear.

| **No. of widgets** | **Before fix render (ms)** | **After fix render (ms)** |
| ------------- |:-------------:|:-------------:|
| 1 | 6 | 6 |
| 3 | 24 | 23 |
| 10 | 137 | 61 |
| 20 | 394 | 136 |
| 30 | 723 | 192 |
| 40 | 1105 | 269 |

Clearly the fix has produced an improvement, moving much closer to **O(*n*)** where *n* is the number of widgets with their own PV connection. Also as expected, when the number of PVs is very low, there is no difference in performance as the widget renders do not add up to being longer than the overarching function call and therefore do not cause a performance detriment.

As Tom Cobb pointed out, the browser is still trying to redraw the DOM when it can based on these updates which leads to the updates being non-contiguous.

Further suggested improvements at this stage:
- use a web worker to process updated PVs and update the store
- throttle updating of the store to 10 Hz (the maximum expected from a PV) and cache all PV updates before updating the store at once. In principle, this would allow all affected widgets to be updated in the same React reconciliation call and prevent redrawing of the DOM interrupting rendering.

**Comment by willrogers** [comment]
It's very easy to implement a simple throttle on updates. I've pushed the branch `throttle` which you can merge into your performance branch for testing (currently updating at about 10 Hz)

If it helps performance we can decide how best to implement it.

**Comment by TimGuiteDiamond** [comment]
Would definitely recommend throttling! Still approximately **O(*n*)** but with a much gentler gradient and noticeable steps where not all updates are performed within the 100ms window. Essentially we are much closer now to **O(*n*)** where *n* is the time taken to update the widget, rather than *n* is the time taken to reconcile the react tree.

Here are results compared with the previously "Fixed" values:

| No. Widgets | Unthrottled (ms) | Throttled (ms) |
| --- | --- | --- |
| 1 | 6 | 9 |
| 10 | 61 | 23 |
| 20 | 136 | 140 |
| 30 | 191 | 154 |
| 40 | 269 | 149 |
| 100 | 1355 | 273 |
| 200 | 3687 | 508 |

Further, it can be seen that for a small number of PVs which all update in the same 100ms window, the widgets update within the same reconciliation call as expected:
![ThrottledWorking](https://user-images.githubusercontent.com/50404435/68770003-42a2b880-061d-11ea-9308-480adc87a649.png)

However, when too many PVs try to update, they are not able to do so within the same 100ms window, the render must be broken up into several calls:
![ThrottledBreaks](https://user-images.githubusercontent.com/50404435/68770078-649c3b00-061d-11ea-9f7a-52e1afb980e8.png)

It is not entirely clear whether it is the SimPVs or the widgets which are causing the update to spill over the 100ms window.

The next check will test increasing numbers of widgets which are all looking at the same PV. This should ensure that any repeated reconciliation calls are caused by delay rather than the PV.

**Comment by TimGuiteDiamond** [comment]
Throttled PVs attached to the same PV update as we would think, with **O(*n*)** time with respect to the number of widgets. See the below table:

| No. Widgets | Render time (ms) |
| --- | --- |
| 10 | 22 |
| 20 | 40 |
| 30 | 54 |
| 40 | 67 |
| 100 | 140 |
| 200 | 213 |

The render time per widget is around 1.2ms plus some overhead, although some PVWidgets were rendering much slower than this on occasion, up to 7ms.

This means that the main impediments on our performance are now:
- the render speed of PV Widget and the component itself
- the speed with which we can update the store

I am yet to test the latest changes with Coniql but this will be coming shortly.

**Comment by TimGuiteDiamond** [comment]
Made an effort to reduce the work done in PV widget by separating out the logic handling styles and extra objects from the code handling the connection. This ultimately proved that our existing code is working reasonably well as there was no noticeable difference found in a range of scenarios. This work can be reviewed in #105 

Further work is required to investigate which hooks/functions are increasing the length of time required to render widgets.

**Comment by TimGuiteDiamond** [comment]
# Coniql Performance Testing

Following the above changes to the coniql code, I have performed some further testing using the Coniql plugin and "real" PVs.

## 100 PVs @ 1Hz

This situation was handled well. Renders take around 1ms so the update rate is handled adequately although it may be split over 2-3 update cycles. Each tree reconciliation has some spare room in it which suggests it could handle more renders if the updates had made their way to the store.

![Throttled_100PVs1Hz](https://user-images.githubusercontent.com/50404435/69140158-df4fd500-0ab9-11ea-8d58-0b7fe73356fa.png)

## 100 PVs @ 2Hz

There is some clear jumping in values at 2Hz and we can see that the thread is starting to fill up as the time taken to read in updates to each PV value an perform a render across 2-3 cycles is starting to approach the update rate of the PVs.

![Throttled_100PVs2Hz](https://user-images.githubusercontent.com/50404435/69140283-1f16bc80-0aba-11ea-8b55-0f17d6707f6b.png)

## 100 PVs @ 5Hz

We are definitely starting to approach capacity here. The browser and app are still responsive which is a massive improvement on previous iterations. The number of renders performed each cycle varies which suggests there is some spare capacity to perform renders in each cycle. Values are jumping quite a lot and not uniform with each other but generally keeping up. Interestingly, **Phoebus** is also skipping some values at this update rate.

![Throttled_100PVs5Hz](https://user-images.githubusercontent.com/50404435/69140484-7ddc3600-0aba-11ea-8d0b-a223850a066b.png)

## 100PVs @ 10Hz

The thread appears to be pretty much as busy as it can get. Each tree reconciliation is performing ~120 updates which is 60 PVWidgets and 60 Readback components. Therefore the value begins to drop behind the true value and will then jump significant values of 10 or 20 in order to stay up. Again, the browser and app remain responsive! Phoebus appears to be throttling to around 0.2s as it doesn't even try to keep up. CS-Studio works very well and shows no issues.

![Throttled_100PVs10Hz](https://user-images.githubusercontent.com/50404435/69140681-e6c3ae00-0aba-11ea-8a95-e0687694c8aa.png)

Another issue appears at 10Hz which is that some values will show "Waiting..." forever and which widgets and how many suffer this fate appears to be unpredictable. This can happen even when there is only one widget. We need to look into this.

![Throttled_50PVs10HzForeverWaiting](https://user-images.githubusercontent.com/50404435/69140758-107cd500-0abb-11ea-94f4-de063ed500c4.png)

## Summary

This is a dramatic improvement on our previous performance, which should not be underestimated. I do think there are still some big gains available if we can isolate the areas slowing us down.

**Comment by TimGuiteDiamond** [comment]
# Coniql vs Simulator

We wanted to see what the difference between Coniql and the simulator are. I tested various numbers of PVs with matching widgets but the interesting results came at the top end, wit 100 PVs.

## Coniql

![ConiqlFunctionCalls100PVs](https://user-images.githubusercontent.com/50404435/69168413-877f9100-0aee-11ea-9dc7-6cc42b7173d6.png)

It can be seen that each "task" is around 1ms and there is no gap between them. With 100PVs, it would therefore take 100ms or so to update all the values. As some time is required for rendering, this is clearly not possible and therefore the values stored begin to fall behind. This is *fine* for now but just a note.

## Basic Ramp Simulator

![SimFunctionCalls100PVs](https://user-images.githubusercontent.com/50404435/69168619-eb09be80-0aee-11ea-8aa4-5c5d6468c0ab.png)

The basic ramp simulator simply adds 1 to the value every time it is called until it reaches 99 and is reset to 0. We can see that many updates, around 10 are being performed each ms which gives us more time to perform the render and still catch all updates. However, this was still not quite happening and some of the values would dominate, leading to values which were out of alignment with each other and making it difficult to judge performance by eye.

Nevertheless, we can see that there must be some significant overhead associated with getting values from Coniql (as expected) and perhaps in the future this could be optimised.

## Advanced Ramp Simulator

![SimDateFunctionCall100PVs](https://user-images.githubusercontent.com/50404435/69168930-6b302400-0aef-11ea-8d5d-3b99729b1f5f.png)

I edited the ramp PV to use the Date() object and give a much more similar output to what we get with Coniql. Values which fall behind are now given the latest value so it looks much cleaner by eye. We can also see that performance is not really affected, with a similar number of updates per ms.

**Comment by TimGuiteDiamond** [comment]
# Testing the effect of rules and macros hooks

It appears that there is not a significant difference between the time taken to render a PV widget with the macros and rules hooks compared to one without those hooks. Here are my approximate numbers for one PVWidget render:

| No. PVs | With Hooks (ms) | Without Hooks (ms) |
| --- | --- | --- |
| 1 | 1.18 | 0.97 |
| 10 | 0.91 | 0.88 |
| 25 | 0.77 | 0.71 |
| 50 | 0.63 | 0.56 |
| 100 | 0.49 | 0.47 |

These numbers were generated using the rampPV at 10Hz. We can see that as the number increases, the difference decreases significantly.

## When is this work happening?

There is a noticeable difference when there is only 1 PV and the Chrome profiler does a good job of showing us where this comes from:

### With hooks

![HooksMeasurement1PV](https://user-images.githubusercontent.com/50404435/69331445-b3188d80-0c4c-11ea-92cc-b58a10ce7bfe.png)

Note the separate function calls to `useMacros`, `useRules` and `useConnection`. Each of these is measured at around 0.12ms.

### Without hooks

![NoHooksPerformance1PV](https://user-images.githubusercontent.com/50404435/69331532-d6433d00-0c4c-11ea-874a-67514775f1df.png)

These function calls, as expected, do not appear when we remove the hooks, although it appears that the time for `useConnection` to call increases slightly.

The expected difference of 0.24ms is quite close to the difference in render time for only one PV, however this effect diminishes as we add more PVs and widgets.

## Summary

These hooks appear to have been cleaned up quite nicely and while they may be adding a small performance cost, are not massively significant.

**Comment by TimGuiteDiamond** [comment]
@willrogers have detailed the key changes on the wiki, take a look and if you're happy it might be time to close this ticket for the time being?
