### ISSUE TITLE
Screen Layout

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#96]
As we move towards having the capability to replicate the absolute layout of CS-Studio/EDM screens, we need to consider how we will actually do this and what it will look like. This will require some new components.

Points which I can think of:

- Match CS-Studio Synoptic/Embed/Detail layout
- How can we provide a mechanism to dictate which part of the screen displays should appear in from an action? (See CS-Studio's "Open OPI" action)
- What will this look like on mobile/flexible type layout? Could we have an "active" pane with options to activate a different pane? Should this inform what it looks like on desktop? Thinking of Malcolm here with its sliding panes for children/parent information
- Scientists often like having many panes open at the same time, how will we handle this?

I will add other points here as I think of them, anyone else feel free to add as well, but I think we can start moving towards this.

Sky's work in #88 is a good step in this direction! I think if this behaviour should be wrapped into an action and performed from the context menu for a shape, graphic or other widget and then merged as a good example.

**Comment by aawdls** [comment]
This was superseded by #128.
